### ISSUE TITLE
Bug: swapExactInput Requires path.length == fees.length, Preventing Multi-Pool Swaps

### ISSUE THREAD

**Issue by jaisonsantos** [sunswapteam/smart-router#7]
I have encountered an issue with the `SmartExchangeRouter` **`TJ4NNy8xZEqsowCBhLvZ45LCqPdGjkET5j`** contract, specifically within the `swapExactInput` function. The function enforces a requirement that `path.length == fees.length`, which imposes a limitation that prevents the use of multiple pools to cover multiple swaps within a single transaction. This constraint leads to inconsistencies and failures when attempting to perform complex swap routes involving multiple pools.

**Issue Details:**

The `swapExactInput` function includes the following require statements:
`require(poolVersion.length == versionLen.length && poolVersion.length > 0, "INVALID_POOL_VERSION.");
require(path.length > 0, "INVALID_PATH");
require(path.length == fees.length, "INVALID_PATH");
`

**Critical Issue:**
The third require statement enforces that the number of fees provided must exactly match the number of tokens in the swap path. However, in scenarios where multiple pools are utilised to cover multiple swaps, the number of fees should correspond to the number of pools (`poolVersion.length`), not necessarily the number of tokens in the path (`path.length`). This discrepancy causes the function to fail when attempting to execute swap routes that involve multiple pools, as the lengths of `path` and `fees` do not align.

**Impact:**
Due to this requirement, it is impossible to:

- **Perform Multi-Pool Swaps:** Routes that require swapping through multiple pools cannot be executed, limiting the flexibility and efficiency of the `SmartExchangeRouter`.

- Optimize Swaps: Users are forced to handle each pool interaction separately, leading to increased gas costs and reduced user experience.

- Implement Complex Trading Strategies: Advanced trading strategies that rely on routing through multiple liquidity pools are unfeasible.

**Example Scenarios:**

1. **Single Pool Swap (Fails):**
  - Path: `[TRX, USDT, TRX]`
  - Fees: `[10, 100]`
  - Result: `path.length == fees.length` (3 != 2) → Fails
  _Note: Even for a single pool covering two swaps, the condition fails._

2. **Multi-Pool Swap (Fails):**
  - Path: `[TRX, USDT, TOKEN_B, MEME, TRX]`
  - Fees: `[10, 10000]`
  - Result: `path.length == fees.length` (5 != 2) → Fails

**Expected Behavior:**
  - `poolVersions.length` should correspond to the number of pools (2 in this case).
  - `fees.length` should correspond to the number of pools (2), not the number of swaps (4).

**Actual Behavior:**
The contract expects fees.length to match path.length, leading to a failure.

**Proposed Solution:**
To resolve this issue, the contract's requirement should be adjusted to align fees.length with the number of pools (`poolVersion.length`) rather than the number of tokens in the path (**path.length**). This adjustment would allow multiple pools to be used within a single swap route without enforcing an unnecessary and conflicting condition.

Adjusted Require Statement:

Replace:
`require(path.length == fees.length, "INVALID_PATH");`

With:
`require(fees.length == poolVersion.length, "INVALID_FEES_LENGTH_DOES_NOT_MATCH_POOL_VERSIONS");`

**Benefits of the Proposed Change:**
  - Flexibility: Allows the use of multiple pools in a single swap route without violating contract requirements.
  - Efficiency: Reduces the need for repetitive fees and simplifies the fee structure.
  - Enhanced User Experience: Enables more complex and optimised trading strategies, improving overall functionality.

**Additional Recommendations:**
  - **Update Documentation:** Ensure that the contract's documentation accurately reflects the relationship between path, poolVersions, and fees.
  - **Provide Examples:** Include examples in the documentation demonstrating how to structure path, poolVersions, and fees for both single-pool and multi-pool swaps.
  - **Emit Detailed Errors:** Modify error messages to provide clearer guidance on the expected relationships between input parameters.

**Steps to Reproduce:**
  1. Prepare Swap Parameters:
    - Define a swap path that includes multiple pools.
    - Assign corresponding fees per pool.
  2. Execute `swapExactInput`:
    - Call the function with the prepared `path`, `poolVersion`, `versionLen`, and `fees`.
  3. Observe Failure:
    - The transaction fails due to the mismatch between `path.length` and `fees.length`.

**Comment by grayfoxd** [comment]
That is not a bug in the contract.
'path.length == fees.length' is a requirement for token to token exchange.
In fact, this fees field is only used for v3 pool confirmation, and only the v3 pool has parameter fee. 
We require a one-to-one correspondence between paths and fees, just to distinguish v3 pools. Other versions of pools only need to make fee = 0.
We will update the document to mark this later.
Thank you for your proposal, best wishes
